### PR TITLE
[DENA-846] remove release-please, mention new release system in the README

### PR DESCRIPTION
**Pull request by MarcinGinszt**

### CODE REVIEW

**Comment by matthewhughes-uw** [comment]
Did we record the discussion around why we picked the semver+release please in the first place? If we need to change this I'm wondering if we could've caught it earlier, i.e. if there's something about our previous process that we can learn from for the future

**Comment by MarcinGinszt** [comment]
@matthewhughes-uw Hey, I think our discussions regarding this matter were 
[here](https://github.com/utilitywarehouse/go-mono/blob/main/services/dev-enablement/opslevel-dependabot-alerts/moon.yml)
and [here](https://utilitywarehouse.slack.com/archives/C34E9HEGG/p1722412544726309)

**Review by matthewhughes-uw — APPROVED** [review]

**Comment by matthewhughes-uw** [comment]
> @matthewhughes-uw Hey, I think our discussions regarding this matter were
[here](https://github.com/utilitywarehouse/go-mono/blob/main/services/dev-enablement/opslevel-dependabot-alerts/moon.yml)

:thinking: that first link just sends me to a file?

**Comment by MarcinGinszt** [comment]
@matthewhughes-uw my bad, fixed

**Review by sbuliarca — APPROVED** [review]

**Pull request merged**
